# Generated by Django 4.2.30 on 2026-09-17 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_active_alter_product_stock_quantity'),
        ('accounts', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('customer', 'product')},
        ),
    ]
